### ISSUE TITLE
Compiling error & after if in "_selection.scss"

### ISSUE THREAD

**Issue by wtrbuit** [thoughtbot/bourbon#591]
I keep getting this error when compiling my CSS with Koala App.

`Syntax error: Invalid CSS after "@if ": expected expression (e.g. 1px, bold), was "& { "`

It seems it doesn’t understand the `&` after the `if` in `_selection.scss`:

``` scss
@if & {
  $before-colons: "&"
}
```

**Comment by fnky** [comment]
Just to update, this is not particular Koala but `libsass`. I get the same error using `gulp-sass` with the latest release of Bourbon.

**Comment by attenzione** [comment]
Getting this error after Bourbon update to 4+ version
sass version 3.3.14 is used

**Comment by wtrbuit** [comment]
@fnky true.

@attenzione Bourbon uses a newer method which requires a newer version of LibSass. Update your LibSass or the app you use to compile.

**Comment by javierjulio** [comment]
I received the same style error for a *non* LibSass project:

`Invalid CSS after "  @if ": expected expression (e.g. 1px, bold), was "& {"`

My app is on Rails 4.2 which does *not* use LibSass, unless I'm mistaken. From reviewing sass-rails it uses sass gem. The project showing this error has latest Bourbon (4.1.1) and sass (3.3.14). Error seems to affect both sass and LibSass uses.

**Comment by tomsanders** [comment]
had the same issue with SASS 3.3.8 and Bourbon 4.1.1
When I updated SASS to 3.4.10 the issue was fixed..

**Comment by pmashchak** [comment]
during upgrade from Rails 3.2 to 4.0 got error Invalid CSS after " @if ": expected expression
after switching SASS from '3.3.13' to '3.4.10' problem was fixed

**Comment by peterbinks** [comment]
Even after upgrading to sass 3.4.11 I'm still getting the `Invalid CSS after " @if ": expected expression (e.g. 1px, bold), was "& {"` error.
